# Generated by Codex on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copilot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdocument",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="user_docs/"),
        ),
    ]
