# Generated by Django 6.0.4 on 2026-04-17 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_configured_sources_organization_regions_and_more'),
        ('regulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('risks_summary', models.JSONField(default=dict)),
                ('actions_taken', models.JSONField(default=list)),
                ('pending_issues', models.JSONField(default=list)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('partial', 'Partial'), ('non_compliant', 'Non-Compliant'), ('under_review', 'Under Review')], default='under_review', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.organization')),
                ('regulations', models.ManyToManyField(blank=True, related_name='reports', to='regulations.regulation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
