import uuid
from django.db import models
from django.conf import settings


TASK_STATUS_CHOICES = [
    ("pending", "Pending"),
    ("in_progress", "In Progress"),
    ("completed", "Completed"),
    ("blocked", "Blocked"),
]

ASSIGNED_ROLE_CHOICES = [
    ("Legal", "Legal"),
    ("IT", "IT"),
    ("Finance", "Finance"),
    ("HR", "HR"),
    ("Compliance", "Compliance"),
    ("Admin", "Admin"),
]


class ComplianceTask(models.Model):
    """Stores tasks generated by the AI generate_tasks() call."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    regulation = models.ForeignKey(
        "regulations.Regulation",
        on_delete=models.CASCADE,
        related_name="tasks",
    )
    risk = models.ForeignKey(
        "risk.Risk",
        on_delete=models.CASCADE,
        related_name="tasks",
    )
    organization = models.ForeignKey(
        "accounts.Organization",
        on_delete=models.CASCADE,
        related_name="tasks",
    )

    # Task content (from AI generate_tasks)
    title = models.CharField(max_length=255)
    description = models.TextField()
    suggested_action = models.TextField(blank=True)
    deadline = models.DateField(null=True, blank=True)
    assigned_role = models.CharField(
        max_length=50, choices=ASSIGNED_ROLE_CHOICES, default="Legal"
    )

    # Assignment (optional user-level assignment)
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assigned_tasks",
    )

    # Execution tracking
    status = models.CharField(max_length=20, choices=TASK_STATUS_CHOICES, default="pending")
    notes = models.TextField(blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["deadline", "-created_at"]

    def __str__(self):
        return self.title
