# Generated by Django 6.0.4 on 2026-04-17 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_configured_sources_organization_regions_and_more'),
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('key_changes', models.TextField(blank=True)),
                ('obligations', models.JSONField(default=list)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='accounts.organization')),
                ('regulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='regulations.regulation')),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
