# Generated by Django 6.0.4 on 2026-04-17 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_configured_sources_organization_regions_and_more'),
        ('analysis', '0001_initial'),
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('impacted_area', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('responsible_role', models.CharField(choices=[('legal', 'Legal'), ('it', 'IT'), ('finance', 'Finance'), ('hr', 'HR'), ('compliance', 'Compliance'), ('admin', 'Admin')], default='compliance', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted')], default='open', max_length=20)),
                ('mitigation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='analysis.analysis')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='accounts.organization')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='regulations.regulation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
