# Generated by Django 6.0.4 on 2026-04-17 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_configured_sources_organization_regions_and_more'),
        ('regulations', '0001_initial'),
        ('risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('suggested_action', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('assigned_role', models.CharField(choices=[('Legal', 'Legal'), ('IT', 'IT'), ('Finance', 'Finance'), ('HR', 'HR'), ('Compliance', 'Compliance'), ('Admin', 'Admin')], default='Legal', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.organization')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='regulations.regulation')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='risk.risk')),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
    ]
